import logging

import torch

from slime.utils.mask_utils import MultiTurnLossMaskGenerator
from slime.utils.processing_utils import load_processor, load_tokenizer

__all__ = ["generate_rollout"]

logger = logging.getLogger(__name__)


TOKENIZER = None
PROCESSOR = None
MASK_GENERATOR = None
SAMPLE_PRINTED = False


def generate_rollout(args, rollout_id, data_buffer, evaluation=False):
    """An example to implement the generate_rollout function for an rule based rm rollout generation.

    Args:
        args: the whole args
        rollout_id: int, the id of the rollout, used for deterministic data generation
        data_buffer: the data buffer to store the generated samples
        evaluation: bool, whether the rollout is for evaluation or not

    Returns:
        list[Sample]: a list of samples generated by the rollout
    """
    assert not evaluation
    assert args.rollout_global_dataset

    global TOKENIZER, PROCESSOR, MASK_GENERATOR, SAMPLE_PRINTED
    if TOKENIZER is None:
        TOKENIZER = load_tokenizer(args.hf_checkpoint, trust_remote_code=True)
        # If using transcriptome adapter, add <transcriptome> as a special token
        # so it tokenizes to a single stable ID (BPE is context-dependent).
        if getattr(args, "transcriptome_embeddings_key", None):
            TOKENIZER.add_special_tokens({"additional_special_tokens": ["<transcriptome>"]})

    if PROCESSOR is None:
        PROCESSOR = load_processor(args.hf_checkpoint, trust_remote_code=True)

    if MASK_GENERATOR is None:
        MASK_GENERATOR = MultiTurnLossMaskGenerator(TOKENIZER, tokenizer_type=args.loss_mask_type)

    samples = data_buffer.get_samples(args.rollout_batch_size)

    for i, sample in enumerate(samples):
        (sample,) = sample
        messages = sample.prompt
        tools = sample.metadata.get("tools", None)

        if PROCESSOR and sample.multimodal_inputs:
            from slime.utils.processing_utils import build_processor_kwargs

            processor_kwargs = build_processor_kwargs(sample.multimodal_inputs)
            processor_output = PROCESSOR(text=messages, **processor_kwargs)
            token_ids = processor_output["input_ids"][0]
            mm_train = {k: v for k, v in processor_output.items() if k not in ["input_ids", "attention_mask"]} or None
            if mm_train:
                sample.multimodal_train_inputs = mm_train
            _, loss_mask = MASK_GENERATOR.get_loss_mask_with_multimodal_alignment(messages, token_ids, tools=tools)
        else:
            token_ids, loss_mask = MASK_GENERATOR.get_loss_mask(messages, tools=tools)

        # Pass pre-computed transcriptome embeddings as training tensors
        if sample.multimodal_inputs and sample.multimodal_inputs.get("transcriptome_embeddings"):
            transcriptome_tensor = torch.tensor(
                sample.multimodal_inputs["transcriptome_embeddings"], dtype=torch.float32
            )
            if sample.multimodal_train_inputs is None:
                sample.multimodal_train_inputs = {}
            sample.multimodal_train_inputs["transcriptome_values"] = transcriptome_tensor

        response_length = MASK_GENERATOR.get_response_lengths([loss_mask])[0]

        sample.tokens = token_ids
        sample.response_length = response_length
        sample.reward = 0
        sample.loss_mask = loss_mask[-response_length:]

        if i == 0 and not SAMPLE_PRINTED:
            logger.info(
                f"sft_rollout::generate_rollout example data: {sample=} (raw){messages=} (raw){token_ids=} (raw){loss_mask=} {response_length=}"
            )
            SAMPLE_PRINTED = True

    return samples
